Delete document dev environment bugfix
Quartech/chat-copilot pull request #167
Opened 2024-11-06 19:13 UTC by hansonchun-quartech

### Description

This PR aims to fix the delete document feature not working on the dev environment. When trying to delete a document on dev, it is unable to find the document entity using the source id. 

Updated so that the entity is fetched using both source and partition id. Seems in local, when using volatile context, the partition id doesn't matter, but in CosmoDB it does. 

Since partition id differs between local and global documents, I also separated out the endpoints - one for local and one for global. This matches the pattern used for import document.

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

2024-11-06 19:53 UTC, mattthiessendev requested changes

2024-11-06 19:53 UTC, mattthiessendev commented on webapi/Controllers/DocumentController.cs
> -        var sourceIdString = sourceId.ToString();
thought: reordering blocks of code can help with readability but, pairing a sweeping style change with logic change makes it difficult to parse what logic is being touched. It would be good to have a separate PR for these sorts of changes.

2024-11-12 20:16 UTC, mattthiessendev approved these changes

2024-11-12 20:16 UTC, mattthiessendev commented on webapi/Controllers/DocumentController.cs
> +    [Route("documents/{sourceId:guid}/global")]
suggestion: let's use a pattern that communicates a document that does not require chat information to be deleted.
`DELETE /documents/{guid}`

2024-11-12 20:16 UTC, mattthiessendev commented on webapi/Controllers/DocumentController.cs
> +    [Route("documents/{sourceId:guid}/{chatId:guid}")]
suggestion: let's use a pattern that communicates a document that requires chat information to be deleted. `DELETE /chats/{chatId:guid}/documents/{sourceId:guid}

2024-11-12 20:16 UTC, mattthiessendev commented on webapi/Controllers/DocumentController.cs
> +        DocumentScopes documentScope,
question: I see this is not being used. Do we need to have this enum as part of the method header?

2024-11-12 20:16 UTC, mattthiessendev commented on webapp/src/libs/services/DocumentImportService.ts
> +        chatId: string,
suggestion: this value could have a `falsy` check so we don't need to pass a boolean.
ex.
```
if (!chatId) {
    // do global logic
} else {
    // do local logic
}
```

2024-11-13 19:31 UTC, hansonchun-quartech commented on webapi/Controllers/DocumentController.cs
> +        DocumentScopes documentScope,
Ah yeah we can remove that

2024-11-13 19:39 UTC, hansonchun-quartech commented on webapp/src/libs/services/DocumentImportService.ts
> +        chatId: string,
I'd prefer to keep the boolean for clarity because it's not immediately evident that !chatId means global.

2024-11-13 21:19 UTC, mattthiessendev commented on webapp/src/libs/services/DocumentImportService.ts
> +        chatId: string,
I don't disagree with this line of thinking

2024-11-13 21:20 UTC, mattthiessendev approved these changes

2024-11-13 22:08 UTC, merged