Dynamic height text area for chat input
Quartech/chat-copilot pull request #200
Opened 2024-11-21 18:39 UTC by GrahamS-Quartech

### Motivation and Context
When constructing a large prompt, it can be difficult to skim your own input with only two lines of text present at a time in the TextArea. This change dynamically adjusts the height based on the text content.

### Description

* Using the textArea ref, dynamically adjust the height based on the content's scrollHeight in the onChange handler.

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

2024-11-21 19:07 UTC, jdtoombs approved these changes

2024-11-21 19:07 UTC, jdtoombs commented
Looks good - I know ChatGPT does it where it has a `max-height` so it doesn't ever get too crazy, but that could be a later thing!

2024-11-21 21:35 UTC, wdavidcamden commented
If we enter Dean's crazy long prompt for the IAF specialization, does it still work?

2024-11-21 21:37 UTC, wdavidcamden requested changes
If we enter Dean's crazy long prompt for the IAF specialization, does it still work?

2024-11-22 00:02 UTC, GrahamS-Quartech commented
![image](https://github.com/user-attachments/assets/1ff86258-df4e-4695-a3fc-563ddd4319b4)

Currently it maxes out at this height, then you can scroll around from there. Wasn't sure if we wanted this thing completely taking over the screen or not.

2024-11-22 00:58 UTC, wdavidcamden commented
> ![image](https://private-user-images.githubusercontent.com/112989452/388737902-1ff86258-df4e-4695-a3fc-563ddd4319b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzczNzAsIm5iZiI6MTczMjIzNzA3MCwicGF0aCI6Ii8xMTI5ODk0NTIvMzg4NzM3OTAyLTFmZjg2MjU4LWRmNGUtNDY5NS1hM2ZjLTU2M2RkZDQzMTliNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwMDU3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTdiOTFlNDMxZWQ0NmQxMGNlZGE1M2QzMzZiODMzZmRkZmYwZjA4NDRkNzlkZTYyZDMwOWE5MjgyNWU4NTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZgL0a_F6j-SnBY_8FmGAVl7RJYrfYvv7Op_D4NgWtgY)
> 
> Currently it maxes out at this height, then you can scroll around from there. Wasn't sure if we wanted this thing completely taking over the screen or not.

Can we add a scrollbar? then it looks good to me :)

2024-11-22 16:57 UTC, JTraill approved these changes

2024-11-22 16:57 UTC, JTraill commented on webapp/src/components/chat/ChatInput.tsx
> +                            textAreaRef.current.style.height = `${textAreaRef.current.scrollHeight}px`;
`textAreaRef.current.style.height` is being set twice here

2024-11-22 17:59 UTC, GrahamS-Quartech commented on webapp/src/components/chat/ChatInput.tsx
> +                            textAreaRef.current.style.height = `${textAreaRef.current.scrollHeight}px`;
This is intentional, try commenting out either line and you will see why.

2024-11-22 19:15 UTC, GrahamS-Quartech commented
> Can we add a scrollbar? then it looks good to me :)

There is a scrollbar when the input has focus, just not shown in that screenshot.

2024-11-22 19:29 UTC, merged