New specialization configs
Quartech/chat-copilot pull request #96
Opened 2024-09-23 23:36 UTC by hansonchun-quartech

### Description

Enables more configurable options for specializations, namely `RestrictResultScope`, `Strictness` and `DocumentCount`.

`RestrictResultScope` is a boolean value. Enabling this will limit responses specific to your data content.
 `Strictness` is a number between 1-5. Strictness sets the threshold to categorize documents as relevant to your queries.
 `DocumentCount` is a number between 3-20. This specifies the number of top-scoring documents from your data index used to generate responses.

### Screenshots

![image](https://github.com/user-attachments/assets/3c257e5d-dfa0-4976-83d2-53af3b157a35)

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

2024-09-25 22:25 UTC, mattthiessendev requested changes
Looks good! The only real sticking point is the user experience of saving settings and causing some confusion when the UI has it's values set to default.

2024-09-25 22:25 UTC, mattthiessendev commented on webapp/src/components/admin/specialization/SpecializationManager.tsx
>              resetSpecialization();
issue: if we are editing a specialization and click the save button, setting the screen back to it's default values will confuse the user. On the nav bar they will see that they are selecting their currently edited specialization but, the reset values will lead them to believe something went wrong and the values were overwritten.

2024-09-25 22:25 UTC, mattthiessendev commented on webapp/src/components/admin/specialization/SpecializationManager.tsx
>              resetSpecialization();
It may be better to just leave the UI as is after the save occurs. This may also be true for the create workflow but, I would be willing to see what the team says.

2024-09-25 23:51 UTC, hansonchun-quartech commented on webapi/Controllers/SpecializationController.cs
> +            this._qAzureOpenAIChatOptions.DefaultStrictness.ToString(CultureInfo.InvariantCulture)
The constructor for the QSpecializationResponse object takes in a parameter of type Dictionary<string, string>. So there is some type conversion going back and forth. Yeah this is kinda weird though, the default Specialization should just return a Specialization type. I'll update the PR.

2024-09-26 00:30 UTC, hansonchun-quartech commented on webapp/src/components/admin/specialization/SpecializationManager.tsx
>              resetSpecialization();
Yes I agree, it was confusing when the values got reset after save. I'll update it to leave it as is after saving

2024-09-26 00:39 UTC, hansonchun-quartech commented on webapi/Services/QSpecializationService.cs
> +            specializationToUpdate!.RestrictResultScope =
I removed the null-forgiving operator and restructured the code for better readability. We are checking `specializationToUpdate` for null at the start of the method.

2024-10-02 18:53 UTC, mattthiessendev approved these changes

2024-10-02 18:53 UTC, mattthiessendev commented on webapi/Services/QSpecializationService.cs
> +        specializationToUpdate.Name = !string.IsNullOrEmpty(qSpecializationMutate.Name)
issue: we need to be setting `specializationToUpdate.Label` in a similar way to the other fields. Right now we are getting the `qSpecializationMutate.label` property and doing nothing with it.

2024-10-02 20:13 UTC, mattthiessendev approved these changes
praise: appreciate you fixing that casing issue!

2024-10-02 20:24 UTC, merged